# RAG AI Project Aliases
alias rag-run="python run.py"
alias rag-test="python test_setup.py"
alias rag-client="python example_client.py"
alias rag-format="black . && isort ."
alias rag-lint="flake8 ."
alias rag-type="mypy ."
alias rag-clean="find . -type d -name __pycache__ -exec rm -rf {} +"
alias rag-install="pip install -r requirements.txt"
alias rag-dev="pip install -e .[dev]"
